# runtime
runtime:
  verbose: true
  clean: true

# tls
tls:
  cert: ./contrib/tls/cert.pem
  key: ./contrib/tls/key.pem

# membership
membership:
  mail:
    send: true
    token: env
    endpoint: https://api.sendgrid.com/v3/mail/send
    email: pandora@mail.sys
    name: Pandora
  database:
    endpoint: http://127.0.0.1:8529
    user: root
    password: root
    database: pandora
  endpoint: 127.0.0.1:2003

# master
master:
  database:
    filepath: ./contrib/master.db
  endpoint: 127.0.0.1:2002

# node
node:
  database:
    filepath: ./contrib/node.db
  dashboard:
    template: ./dashboard/index.html
  meta:
    name: Pandora university
    email: pandora@mail.sys
  endpoint: 127.0.0.1:2004

# discovery
discovery:
  database:
    filepath: ./contrib/discovery.db
  broker:
    endpoint: nats://127.0.0.1:4222
    user: root
    password: root
  endpoint: 127.0.0.1:2001
