# runtime
runtime:
  verbose: true
  clean: true

# mail
mail:
  send: false
  token: ''
  endpoint: https://api.sendgrid.com/v3/mail/send
  email: pandora@doesnotexist.system
  name: Pandora
  templates:
    account:
      created: ./pkg/utils/mail/templates/account/created.html
      recovery: ./pkg/utils/mail/templates/account/recovery.html
  subjects:
    account:
      created: Pandora account is created
      recovery: Pandora account recovery

# database
database:
  endpoint: http://localhost:8529
  user: root
  password: root
  database: pandora

# broker
broker:
  endpoint: nats://localhost:4222
  user: root
  password: root

# secure
secure:
  PSSMessage: secret
  JWTKey: secret

# discovery
discovery:
  port: 2002

# api
api:
  port: 2001
