# runtime
verbose: true
clean: true

# mail
mail:
  token: ''
  endpoint: https://api.sendgrid.com/v3/mail/send
  email: pandora@doesnotexist.system
  name: Pandora
  templates:
    account:
      created: ./pkg/utils/mail/templates/account/created.html
      recovery: ./pkg/utils/mail/templates/account/recovery.html
  subjects:
    account:
      created: Pandora account is created
      recovery: Recovery Pandora account

# database
db:
  file: ./contrib/pandora.db

# broker
broker:
  url: nats://localhost
  port: 4222

# secure
secure:
  PSSMessage: secret
  JWTKey: secret

# api
api:
  port: 2001
