# runtime
verbose: true

# sendgrid
sendgrid:
  token: ''
  endpoint: 'https://api.sendgrid.com/v3/mail/send'
  email: 'pandora@doesnotexist.system'
  name: 'Pandora'

# rsa
rsa:
  PSSMessage: 'secret'

# database
db:
  file: './contrib/pandora.db'

# api
api:
  host: 'localhost'
  port: 2001
