# runtime
runtime:
  verbose: true
  clean: true

# mail
mail:
  send: false
  token: token
  endpoint: https://api.sendgrid.com/v3/mail/send
  email: pandora@doesnotexist.system
  name: Pandora
  templates:
    account:
      created: ./pkg/utils/mail/templates/account/created.html
      recovery: ./pkg/utils/mail/templates/account/recovery.html
  subjects:
    account:
      created: Pandora account is created
      recovery: Pandora account recovery

# database
database:
  endpoint: http://localhost:8529
  user: root
  password: root
  database: pandora

# broker
broker:
  endpoint: nats://localhost:4222
  user: root
  password: root

# secure
secure:
  key: secret
  salt: salt
  jwt: jwt

# validator
validator:
  broker:
    endpoint: nats://localhost:4222
    user: root
    password: root
  tracker: localhost:2001

# tracker
tracker:
  port: 2001

# node
node:
  backup:
    file: backup.json
  discovery:
    endpoint: http://localhost:2002

# discovery
discovery:
  port: 2002

# api
api:
  port: 2001
