# runtime
runtime:
  verbose: true
  clean: false

# membership
membership:
  mail:
    send: false
    token: env
    endpoint: https://api.sendgrid.com/v3/mail/send
    email: pandora@doesnotexist.system
    name: Pandora
    templates:
      # todo rename
      credentials: ./pkg/utils/mail/templates/credentials.html
    subjects:
      credentials: Credentials
  database:
    endpoint: http://localhost:8529
    user: root
    password: root
    database: pandora
  endpoint: localhost:2003

# validator
master:
  endpoint: localhost:2002

# node
node:
  dashboard:
    template: ./dashboard/index.html
  meta:
    name: State University of Aerospace Instrumentation
    email: guap@mail.sys
    secret_key: env
  port: 2004

# discovery
discovery:
  broker:
    endpoint: nats://localhost:4222
    user: root
    password: root
  endpoint: localhost:2001
