# runtime
runtime:
  verbose: true
  clean: true

# mail
mail:
  send: true
  token: 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
  endpoint: https://api.sendgrid.com/v3/mail/send
  email: pandora@doesnotexist.system
  name: Pandora
  templates:
    credentials: ./pkg/utils/mail/templates/credentials.html
  subjects:
    credentials: Credentials

# dashboard
dashboard:
  template: ./dashboard/index.html

# database
database:
  endpoint: http://localhost:8529
  user: root
  password: root
  database: pandora

# broker
broker:
  endpoint: nats://localhost:4222
  user: root
  password: root

# membership
membership:
  endpoint: localhost:2003

# validator
master:
  endpoint: localhost:2002

# node
node:
  endpoint: localhost:2004
  full_name: State University of Aerospace Instrumentation
  secret_key: secret
  email: guap@doesnotexists.system

# discovery
discovery:
  endpoint: localhost:2001
