# runtime
runtime:
  verbose: true
  clean: true

# tls
tls:
  cert: ./contrib/docker/tls/cert.pem
  key: ./contrib/docker/tls/key.pem

# membership
membership:
  mail:
    send: false
    token: env
  database:
    endpoint: http://arangodb:8529
    user: root
    password: root
    database: pandora
  endpoint: kit:2003

# master
master:
  endpoint: kit:2002

# node
node:
  database:
    filepath: ./contrib/node.db
  dashboard:
    template: ./dashboard/index.html
  meta:
    name: Pandora university
    email: pandora@mail.sys
  endpoint: kit:2004

# discovery
discovery:
  broker:
    endpoint: nats://nats:4222
    user: root
    password: root
  endpoint: kit:2001
