name: main
on: [push]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.13.7
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.7
        id: go
      - name: check out code
        uses: actions/checkout@v1
      - name: cache dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
      - name: test
        run: go test -v -count=1 -race -cover ./...

  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.13.7
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.7
        id: go
      - name: check out code
        uses: actions/checkout@v1
      - name: install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.23.2
      - name: run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...
